export enum ActionTypes {
  SET_TEXTURES = 'SET_TEXTURES',
  SET_BUFFERS = 'SET_BUFFERS',
  SET_BUFFERS_ORDER = 'SET_BUFFERS_ORDER',
  SET_OUTPUT_BUFFER = 'SET_OUTPUT_BUFFER',
  SELECT_BUFFER = 'SELECT_BUFFER',
  RESIZE = 'RESIZE',
  SET_ERRORS = 'SET_ERRORS',
}
